// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { enableGlobalFallbackMode, fetchWithTimeout, SUPABASE_TIMEOUT_MS } from '@/lib/safeRuntimeData';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!hasSupabaseConfig) {
  enableGlobalFallbackMode();
  console.warn("Supabase env vars are missing. App switched to fallback mode.");
}

const RESILIENT_SUPABASE_URL = SUPABASE_URL || "https://invalid.local";
const RESILIENT_SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY || "missing-publishable-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseFetch: typeof fetch = (input, init) =>
  fetchWithTimeout(input, init, {
    timeoutMs: SUPABASE_TIMEOUT_MS,
    markGlobalFallbackOnError: true,
  });

export const supabase = createClient<Database>(RESILIENT_SUPABASE_URL, RESILIENT_SUPABASE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: supabaseFetch,
  },
});